dist: bionic
language: python

services:
    - docker

install:
    - pip install jinja2 docker pyyaml

jobs:
  include:
    - stage: build Graphene Docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd Tools/gsc
      - make
      - docker build -t vahldiek/graphene:aks -f images/graphene_aks.latest.dockerfile images/
      - docker push vahldiek/graphene:aks