name: Docker Image CI

on:
  push:
    branches: [ github-workflow ]
  pull_request:
    branches: [ github-workflow ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8        
    - name: Install dependencies
      run: |
        pip install jinja2 pyyaml docker
    - name: Build the Docker image
      env: # Or as an environment variable
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        cd Tools/gsc
        make
        docker build -t vahldiek/graphene:aks -f images/graphene_aks.latest.dockerfile images/
        docker push vahldiek/graphene:aks
